{
  "definitions": {
    "ContactType": {
      "type": "object",
      "properties": {
        "ADGuid": { "type": "string", "nullable": true },
        "ADLogin": { "type": "string", "nullable": true },
        "AccountId": { "type": "string", "nullable": true },
        "Active": { "type": "boolean", "nullable": true },
        "AssistantEmail": { "type": "string", "nullable": true },
        "AssistantName": { "type": "string", "nullable": true },
        "AssistantPhoneNumber": { "type": "string", "nullable": true },
        "Comment": { "type": "string", "nullable": true },
        "ContactStatus": { "type": "string", "nullable": true },
        "Contractor": { "type": "boolean", "nullable": true },
        "CorrespondingOrganization": { "type": "string", "nullable": true },
        "Credential": { "type": "string", "nullable": true },
        "DepartmentName": { "type": "string", "nullable": true },
        "Email": { "type": "string", "nullable": true },
        "Fax": { "type": "string", "nullable": true },
        "FirstName": { "type": "string", "nullable": true },
        "Gender": { "type": "string", "nullable": true },
        "Id": { "type": "string", "nullable": true },
        "InterestString": { "type": "string", "nullable": true },
        "LastName": { "type": "string", "nullable": true },
        "MailingCity": { "type": "string", "nullable": true },
        "MailingCountry": { "type": "string", "nullable": true },
        "MailingPostalCode": { "type": "string", "nullable": true },
        "MailingState": { "type": "string", "nullable": true },
        "MailingStreet": { "type": "string", "nullable": true },
        "MarketPlaceDateTimeToUHC": { "type": "string", "format": "date-time", "nullable": true },
        "MarketPlaceLogin": { "type": "string", "nullable": true },
        "MarketPlaceLoginStatus": { "type": "string", "nullable": true },
        "MedicareId": { "type": "string", "nullable": true },
        "MiddleName": { "type": "string", "nullable": true },
        "MobilePhone": { "type": "string", "nullable": true },
        "NeverCall": { "type": "boolean", "nullable": true },
        "NeverEmail": { "type": "boolean", "nullable": true },
        "NeverMail": { "type": "boolean", "nullable": true },
        "NeverUHCNews": { "type": "boolean", "nullable": true },
        "PhoneNumber": { "type": "string", "nullable": true },
        "PhysicialSpeciality": { "type": "string", "nullable": true },
        "PreferredCommunication": { "type": "string", "nullable": true },
        "PreferredName": { "type": "string", "nullable": true },
        "ProductRequestString": { "type": "string", "nullable": true },
        "SATDisclaimerDate": { "type": "string", "format": "date-time", "nullable": true },
        "Salutation": { "type": "string", "nullable": true },
        "SecondaryJobTitle": { "type": "string", "nullable": true },
        "SecurityComment": { "type": "string", "nullable": true },
        "SecurityEndDate": { "type": "string", "format": "date-time", "nullable": true },
        "SecurityStartDate": { "type": "string", "format": "date-time", "nullable": true },
        "ShippingCity": { "type": "string", "nullable": true },
        "ShippingCountry": { "type": "string", "nullable": true },
        "ShippingPostalCode": { "type": "string", "nullable": true },
        "ShippingState": { "type": "string", "nullable": true },
        "ShippingStreet": { "type": "string", "nullable": true },
        "SiebelContactId": { "type": "string", "nullable": true },
        "SiteType": { "type": "string", "nullable": true },
        "Source": { "type": "string", "nullable": true },
        "Suffix": { "type": "string", "nullable": true },
        "Title": { "type": "string", "nullable": true },
        "UHCInactivatedBy": { "type": "string", "nullable": true },
        "iPlanContactId": { "type": "string", "nullable": true }
      },
      "additionalProperties": false
    }
  }
}
